version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=your_secret_key
      - DEBUG=1
      - DB_NAME=your_db_name
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_HOST=your_db_host
      - DB_PORT=your_db_port

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  nginx:
    build: .
    container_name: todo-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
